services:
  api:
    build:
      context: ./app
      dockerfile: Dockerfile
      network: host
    environment:
      DB_URI: mysql+pymysql://app:pass@db/receipts
      TESSDATA_PREFIX: /usr/share/tesseract-ocr/5/tessdata
    ports: ["8000:8000"]
    volumes:
      - ./models:/models          # in case you drop Paddle weights here
    depends_on: [db]

    # Uncomment to enable GPU OCR (needs nvidia‑container‑toolkit)
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           capabilities: [gpu]

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: receipts
      MYSQL_USER: app
      MYSQL_PASSWORD: pass
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

volumes:
  db_data:
